### ISSUE TITLE
UAM(자율주행차, 드론)의 프라이버시 관리, 보안 플랫폼 등과 MDM의 특허 조사

### ISSUE THREAD

**Issue by eradegus** [mmlab-uran/Task-Board#4]
## Summary
- UAM(자율주행차, 드론)의 프라이버시 관리, 보안 플랫폼 등과 MDM의 특허 조사

**Comment by tiop7** [comment]
[URAN 특허 조사.pdf](https://github.com/mmlab-uran/Task-Board/files/6965990/URAN.pdf)
