### ISSUE TITLE
오프라인 미팅 회의록 공유

### ISSUE THREAD

**Issue by sungmin-net** [mmlab-uran/Task-Board#8]
기존에 메일로 공유된 것들 미리 옮깁니다. 이후에는 경헌씨가 코멘트로 최신화해주세요.

★ '21.07.16 - Kick off 미팅
1. [현수] 과제 소개 진행

2. [현수] Wiki 생성 관련: iphone 에서 slack이 안되는 경향이 있어서, 제안서 작성시에 만든 slack 말고, 새로 생성해서 공유 예정
* 참고: 제안서 작성용 링크 slack, https://app.slack.com/client/T01U7030N7R/C01UJLS581K

3. [현수] 올해 할일 : 특허 3개, 이슈분석서 2개(드론 등 시스템 관점 / 프라이버시 관점)
3.1. [현수] 올해 과제 진행 계획을 간트차트로 만들어서 공유
3.2. [성민] 첫 특허는 공공 공중 보안을 위한 서버리스 MDM으로 작성 예정

4. [현수] 과제 운영 관련: 2주마다 오프라인 미팅
4.1. 다음 미팅은 7.29(목) 14:00

5. [성민] APM 프로토타이핑 관련: Android MDM 시연 및 소개
5.1. [성민] 다음 미팅에 APM 프로토타입 개발 계획 및 진행사항 공유 예정

6. 재현, 경헌은 다음 미팅까지 TODO 없음

★ '21.07.29 - 정기미팅
1. [현수] 과제 관련 행정 이슈 소개
1.1 협약은 9월 이후 완료
1.2 자동차 및 무인이동체 보안 워크샵 - 링크로 참여
1.3 Redmine 사용 예정

2. [성민] 이전에 교수님과 나눴던 과제 관련 이야기 전달
2.1  APM 관련 TopConf 논문 준비

3. [재현] APM server과 UAM, UAM과 Device 간의 통신 체계 제시
3.1 UAM과 Device 간의 통신에서 UAM의 명령으로 Device를 제어

4. [성민] 특허 출현의 프로세스 소개

5. 다음 미팅은 8월 12일 14:00

TODO. [성민] UAM과 Device간의 통신 프로토타입의 대략적인 설계
            [재현, 현수] UAM(자율주행차, 드론)의 attack issue 조사
            [경헌] UAM(자율주행차, 드론)의 프라이버시 관리, 보안 플랫폼 등과 MDM의 특허 조사
            git hub의 org 계정 생성

★ '21.08.12 - 정기미팅
1. [재현] 드론 threat 소개 - threat 분류에 관해 초점을 둠.
1.1 [현수] 우리가 해야할 과제에서 threat model을 어떻게 다룰지 고민

2. [성민] 현재 개발 진행 상황
2.1 Github에 있는 코드로 설명(server와 안드로이드 앱)

3. [경헌] CAN bus에 관한 IDS 정리 - 드론에서 사용하지 않겠지만, 알고 있을 필요가 있음.
3.1 이전의 자동차, 무인이동체 보안 워크숍에서 김휘강 교수님 발표를 참조.
3.2 CAN bus와 attack point, method 소개 - 조금 더 정리 필요

4. [현수] 서버리스 MDM과 APM 2가지의 특허 주제 제안
4.1 서버리스 MDM의 구성에 관련해 토론(출퇴근 기록을 서버로 받아야 함. 공간별로 세분화해서 관리 등)
4.2 [현수] APM 대표 도면 제시 - 1) 서버가 있는경우 - zone별 policy를 받아서 UAM이 판단 + UAM이 위치 정보를 주면 서버가 판단
                                                  - 2) 서버가 없는 경우 - zone별 policy를 받아서 UAM이 판단
4.2.1 UAM 내부에서는 일반적인 MDM
4.2.2 JSON은 파일 포맷으로 효율적
4.2.3 policy의 형태는 (위치, 시간, 모드)를 포함. (event policy는 따로)
4.2.3.1 모드는 추가적인 구성 필요(모드별로 권한 부여)

5. [경헌] UAM(자율주행차, 드론)의 프라이버시와 MDM의 특허 조사 발표
5.1 드론 프라이버시 관련해서 우리 주제와 비슷한 몇몇의 특허 확인.

6. 다음 미팅은 8월 26일 14:00

TODO. [현수] 대표 도면 완성, 교수님께 월간 보고
            [ALL] docs에 발명 제안서 각자 부분 작성

**Comment by eradegus** [comment]
https://github.com/mmlab-uran/Task-Board/wiki 에 페이지 별 기록중입니다. (이후 다른 저장소 준비되면 이관예정입니다.)

**Comment by sungmin-net** [comment]
엇 위키에 적고 계셨네요.;; 이슈 닫겠습니다.
